### ISSUE TITLE
Licence in a LICENSE file.

### ISSUE THREAD

**Issue by CreativeCylon** [powervr-graphics/PowerVR-Series1#1]
It appears that this is the licence of this repo.
https://github.com/powervr-graphics/PowerVR-Series1/blob/1f702112a499b68f9a9a3a51fce84e7fe56d43af/Documentation/3DCC-Readme.txt#L1-L18

Can this be placed in a `LICENSE` file in root as is common for Github repos?
@LawG4

**Comment by pnyaa** [comment]
Ahh Apologies, The Source code is release by us under MIT (Which I've now added into the LICENSE file as recommended) That license is from an executable provided alongside the documentation. We pulled this forward to the root of documentation to make it more visible for 3DCC

**Comment by CreativeCylon** [comment]
Also. Would it be possible for this to have an open source licence like GPL so people can actually use this?

Reading: " This software may not be modified, **disassembled** or reverse engineered in any way without written authorization from the author, " I don't even know if I can look at the source.

Is attempting to understand the code a form of reverse engineering? What if someone looked at this got familiar with it and wrote something based on this, is that interpreted as modifying the source and a violation of the licence?

**Comment by pnyaa** [comment]
Thanks for the feedback, I've added clarification that specifies that the readme only applies to specific executables, and all source code is under the license in LICENSE
