### ISSUE TITLE
I'll give you this...

### ISSUE THREAD

**Issue by Soap-Sonic** [powervr-graphics/PowerVR-Series1#4]
This could be the next Dreamcast

**Comment by leilei-** [comment]
no

**Comment by Soap-Sonic** [comment]
Then what?

**Comment by Soap-Sonic** [comment]
And if u say Saturn or genesis/megadrive that's awesome

**Comment by leilei-** [comment]
This repository is about the PCX1/2. These are old, 3d-only expansion cards from 1996/1997.   Dreamcast uses a chip based on Series 2 hardware, which is greatly more capable at blending (among other stuff). 

While so many associate the PowerVR brand with Dreamcast's hype and nostalgia, this repository DOES NOT mean:

- New Dreamcast products

- New Saturn products

- Faster/better Dreamcast

**Comment by Soap-Sonic** [comment]
_Heh heh heh. And look at all the work I did while you boys weren’t looking.

_

**Comment by Soap-Sonic** [comment]
Btw I did a test run to see if ur little machine was broken on purpose… results just came back. Not looking good for powervr
